"""Alembic 迁移模板。"""

"""add risk_records timestamp

Revision ID: 3b4be866a3a9
Revises: dd0b8a308051
Create Date: 2026-07-01 17:37:12.362201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b4be866a3a9'
down_revision: Union[str, None] = 'dd0b8a308051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('risk_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_records', 'updated_at')
    op.drop_column('risk_records', 'created_at')
    # ### end Alembic commands ###
