"""Alembic 迁移模板。"""

"""initial schema

Revision ID: 7805e17097b9
Revises: 
Create Date: 2026-07-01 17:26:55.967577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7805e17097b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('responsible_person', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('contract_no')
    )
    op.create_table('source_files',
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('upload_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('contracts',
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('type_judge_basis', sa.String(length=200), nullable=True),
    sa.Column('party_a', sa.String(length=200), nullable=True),
    sa.Column('party_b', sa.String(length=200), nullable=True),
    sa.Column('our_role', sa.String(length=10), nullable=True),
    sa.Column('signing_date', sa.Date(), nullable=True),
    sa.Column('contract_period', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_uppercase', sa.String(length=100), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('acceptance_terms', sa.Text(), nullable=True),
    sa.Column('breach_terms', sa.Text(), nullable=True),
    sa.Column('warranty_terms', sa.Text(), nullable=True),
    sa.Column('ip_terms', sa.Text(), nullable=True),
    sa.Column('other_key_terms', sa.Text(), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('source_file_name', sa.String(length=300), nullable=True),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_no'], ['projects.contract_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_no', 'contracts', ['contract_no'], unique=False)
    op.create_index('idx_contracts_type', 'contracts', ['contract_no', 'contract_type'], unique=False)
    op.create_table('risk_records',
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_by', sa.String(length=50), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_no'], ['projects.contract_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acceptance_reports',
    sa.Column('acceptance_no', sa.String(length=100), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('acceptance_type', sa.String(length=10), nullable=True),
    sa.Column('type_judge_basis', sa.String(length=200), nullable=True),
    sa.Column('acceptance_content', sa.Text(), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('acceptance_result', sa.String(length=20), nullable=True),
    sa.Column('pair_report_id', sa.UUID(), nullable=True),
    sa.Column('comparison_result', sa.String(length=10), nullable=True),
    sa.Column('content_diff_detail', sa.Text(), nullable=True),
    sa.Column('date_logic', sa.String(length=10), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('source_file_name', sa.String(length=300), nullable=True),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_no'], ['projects.contract_no'], ),
    sa.ForeignKeyConstraint(['pair_report_id'], ['acceptance_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisons',
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('front_contract_id', sa.UUID(), nullable=True),
    sa.Column('back_contract_id', sa.UUID(), nullable=True),
    sa.Column('front_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('back_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_diff', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('amount_match', sa.String(length=10), nullable=True),
    sa.Column('payment_match', sa.String(length=10), nullable=True),
    sa.Column('delivery_match', sa.String(length=10), nullable=True),
    sa.Column('acceptance_match', sa.String(length=10), nullable=True),
    sa.Column('other_match', sa.String(length=10), nullable=True),
    sa.Column('payment_diff_detail', sa.Text(), nullable=True),
    sa.Column('delivery_diff_detail', sa.Text(), nullable=True),
    sa.Column('acceptance_diff_detail', sa.Text(), nullable=True),
    sa.Column('other_diff_detail', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('compared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['back_contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_no'], ['projects.contract_no'], ),
    sa.ForeignKeyConstraint(['front_contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_line_items_contract', 'line_items', ['contract_id'], unique=False)
    op.create_table('line_item_comparisons',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('front_item_id', sa.UUID(), nullable=True),
    sa.Column('back_item_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=True),
    sa.Column('front_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('back_quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('quantity_diff', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('front_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('back_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_diff', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('front_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('back_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_diff', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['back_item_id'], ['line_items.id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['front_item_id'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item_comparisons')
    op.drop_index('idx_line_items_contract', table_name='line_items')
    op.drop_table('line_items')
    op.drop_table('comparisons')
    op.drop_table('acceptance_reports')
    op.drop_table('risk_records')
    op.drop_index('idx_contracts_type', table_name='contracts')
    op.drop_index('idx_contracts_no', table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('source_files')
    op.drop_table('projects')
    op.drop_table('audit_log')
    op.drop_table('admins')
    # ### end Alembic commands ###
