"""Alembic 迁移模板。"""

"""add contracts timestamp

Revision ID: dd0b8a308051
Revises: 7805e17097b9
Create Date: 2026-07-01 17:33:35.667822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd0b8a308051'
down_revision: Union[str, None] = '7805e17097b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('contracts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'updated_at')
    op.drop_column('contracts', 'created_at')
    # ### end Alembic commands ###
